version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9r3s5p8
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t <NAME YOU WANT YOUR IMAGE FILE> .
      - docker tag <NAME OF YOUR IMAGE FILE>:latest public.ecr.aws/q9r3s5p8/<NAME OF YOUR IMAGE FILE>:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/q9r3s5p8/<NAME OF YOUR IMAGE FILE>:latest

artifacts:
    files: imagedefinitions.json

